name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make Hp21
      run: make MODEL=21
    - name: make Hp22
      run: make MODEL=22
    - name: make Hp25
      run: make MODEL=25
    - name: make Hp27
      run: make MODEL=27
    - name: make Hp29
      run: make MODEL=29
    - name: make Hp31
      run: make MODEL=31
    - name: make Hp32
      run: make MODEL=32
    - name: make Hp33
      run: make MODEL=33
